name: PMCAprilFoolsDay
version: ${project.version}
main: com.popupmc.aprilfoolsday.AprilFoolsDay
description: A purely cosmetic plugin that modifies quite a lot of packets to the client for funny and sometimes mildly annoying effects. Planned to be enabled by default for non-moderators and non-admins but to allow anyone to toggle it.
authors: [junebug12851,lelesape]
api-version: 1.15
depend:
  - ProtocolLib

commands:
  afd-spawn:
    description: AprilFoolsDay Spawn (A debugging command for expiremental functionality)
    usage: /afd-spawn
  toggle-joke:
    description: OnToggleJokeCommand April Fools Day Joke
    usage: /toggle-joke
