name: PMCAprilFoolsDay
version: ${project.version}
main: com.popupmc.aprilfoolsday.AprilFoolsDay
description: A purely cosmetic plugin that modifies quite a lot of packets to the client for funny and sometimes mildly annoying effects. Planned to be enabled by default for non-moderators and non-admins but to allow anyone to toggle it.
authors: [junebug12851,lelesape]
api-version: 1.15
depend: [ProtocolLib]

commands:
  aprilFoolsDay:
    description: AprilFoolsDay main command.
    aliases: [afd]
    usage: Command was not registered properly.
  toggle-joke:
    description: OnToggleJokeCommand April Fools Day Joke.
    usage: /toggle-joke

permissions:
  aprilFools.version:
    description: Allows you to checck the plugin's current version.
    default: op
  aprilFools.reload:
    description: Allows you to reload the plugin and its files.
    default: op
  aprilFools.toggle.self:
    description: Allows a player to toggle their own joke status.
    default: op
  aprilFools.toggle.others:
    description: Allows a player to toggle another player's joke status.
    default: op
  aprilFools.default.bypass:
    description: Allows a player to bypass the joke default status.
    default: op
  aprilFools.*:
    description: Gives access to every permission available
    default: op